baseURL = "http://example.org/"
languageCode = "en-us"
theme = "hugo-steam"
title = "Dream Possible"
[[menu.main]]
identifier = "media"
name = "傳 媒 報 導"
url = "/media/"
weight = 6
[[menu.main]]
identifier = "coachtoserve"
name = "Coach to serve"
url = "/coachtoserve/"
weight = 5
[[menu.main]]
identifier = "payloveforward"
name = "Pay love forward"
url = "/payloveforward/"
weight = 4
[[menu.main]]
identifier = "lifegrow"
name = "生 命 成 長"
pre = "<i class='fa fa-road'></i>"
url = "/lifegrow/"
weight = 3
[[menu.main]]
identifier = "aboutus"
name = "關 於 我 們"
url = "/aboutus/"
weight = 1
[[menu.main]]
identifier = "course"
name = "課 程"
url = "/course/"
weight = 2
[[menu.main]]
identifier = "contactus"
name = "聯 絡 我 們"
pre = "<i class='fa fa-road'></i>"
url = "/contactus/"
weight = 7
[[menu.lifegrow]]
	name = "工作坊及活動花絮"
	weight = -90
	url = "https://www.facebook.com/pg/339.hk/photos/?tab=albums"

[[menu.media]]
	name = "YouTube頻道"
	weight = -90
	url = "https://www.youtube.com/user/Dreamspossible?feature=mhum"

[[menu.contactus]]
	name = "行事曆"
	weight = -90
	url = "http://calendar.dreamspossible.hk/"

# [[menu.course]]
# 	name = "<img style='filter: brightness(0) invert(1);' src='/img/course_icon.png'>賽馬會青年更生教練課程"
# 	weight = -70
# 	url = ""

[params]
backtotopstr = "Back to top"
bio = "programmer - blogger - coffee aficionado"
bitbucket = ""
copyright = "Released under the MIT license."
customcss = []
customjs = []
description = "Your description of the blog"
dpicon = "/img/logo.svg"
facebook = ""
favicon = "favicon.ico"
fbicon = "/img/fb_icon.svg"
gitlab = ""
googleplus = ""
instagram = ""
keepreadingstr = "Keep reading"
linkedin = ""
location = ""
name = "John Doe"
pagenotfoundtitle = "404 - Page not found"
sharestr = "Share"
subtitle = "幸福/從感恩開始"
themecolor = "green"
title = "自在社"
youtubeicon = "/img/youtube_icon.svg"
[[params.homeimg]]
path = "img/loopbanner1.jpg"
[[params.homeimg]]
path = "https://pbs.twimg.com/media/DKV68fvUIAAQEXJ.jpg"
[[params.homeimg]]
path = "https://images7.alphacoders.com/691/691161.png"
[[params.homeimg]]
path = "https://images.alphacoders.com/725/725119.png"
