baseURL = "http://example.org/"
languageCode = "en-us"
theme = "hugo-steam"
title = "Dream Possible"
[[menu.contactus]]
name = "行事曆"
url = "http://calendar.dreamspossible.hk/"
weight = 2
[[menu.lifegrow]]
name = "工作坊及活動花絮"
url = "https://www.facebook.com/pg/339.hk/photos/?tab=albums"
weight = 2
[[menu.main]]
identifier = "lifegrow"
name = "生 命 成 長 \n 免 費 工 作 坊"
pre = "<i class='fa fa-road'></i>"
url = "/lifegrow/"
weight = 3
[[menu.main]]
identifier = "payloveforward"
name = "Pay Love Forward \n 義 工 團 隊"
url = "/payloveforward/"
weight = 4
[[menu.main]]
identifier = "coachtoserve"
name = "Coach To Serve \n 服 務 社 會"
url = "/coachtoserve/"
weight = 5
[[menu.main]]
identifier = "media"
name = "傳 媒 報 導"
url = "/media/"
weight = 6
[[menu.main]]
identifier = "aboutus"
name = "關 於 我 們"
url = "/aboutus/"
weight = 1
[[menu.main]]
identifier = "course"
name = "生 命 工 作 者 \n 課 程"
url = "/course/"
weight = 2
[[menu.main]]
identifier = "contactus"
name = "聯 絡 我 們"
pre = "<i class='fa fa-road'></i>"
url = "/contactus/"
weight = 7
[[menu.media]]
name = "YouTube頻道"
url = "https://www.youtube.com/user/Dreamspossible?feature=mhum"
weight = 2
[params]
dpicon = "/img/logo.svg"
favicon = "favicon.ico"
fbicon = "/img/fb_icon.svg"
fblink = "https://www.facebook.com/339.hk/"
themecolor = "green"
title = "自在社"
youtubeicon = "/img/youtube_icon.svg"
youtubelink = "https://www.youtube.com/user/Dreamspossible?feature=mhum"
[[params.homeimg]]
path = "img/loopbanner1.jpg"
