baseURL = "http://example.org/"
languageCode = "en-us"
title = "Dream Possible"

theme = "hugo-steam"

[[menu.main]]
    name = "關 於 我 們"
    weight = -110
    identifier = "aboutus"
    url = "/aboutus/"
[[menu.main]]
    name = "聯 絡 我 們"
    pre = "<i class='fa fa-road'></i>"
    weight = -50
	identifier = "contactus"
    url = "/contactus/"
[[menu.main]]
    name = "課 程"
    weight = -100
    identifier = "course"
    url = "/course/"
[[menu.main]]
    name = "生 命 成 長"
    pre = "<i class='fa fa-road'></i>"
    weight = -90
	identifier = "lifegrow"
    url = "/lifegrow/"
[[menu.main]]
    name = "傳 媒 報 導"
    weight = -60
    identifier = "media"
    url = "/media/"
[[menu.main]]
    name = "Pay love forward"
    weight = -80
	identifier = "payloveforward"
    url = "/payloveforward/"

[params]
	title = "自在社"
	subtitle = "幸福/從感恩開始"
	copyright = "Released under the MIT license."

	# You can choose between green, orange, red and blue.
	themecolor = "green"

	# Link custom assets relative to /static
	favicon   = "favicon.ico"
	customCSS = []
	customJS  = []

	# To provide some metadata for search engines and the about section in the footer
	# feel free to add a few information about you and your website.
	name = "John Doe"
	bio = "programmer - blogger - coffee aficionado"
	description = "Your description of the blog"
	
	# Link your social networks (optional)
	location = ""
	#twitter = "spf13"
	linkedin = ""
	googleplus = ""
	facebook = ""
	instagram = ""
	#github = "spf13"
	gitlab = ""
	bitbucket = ""

	# Customize or translate the strings
	keepReadingStr = "Keep reading"
	backtotopStr = "Back to top"
	shareStr = "Share"
	pageNotFoundTitle = "404 - Page not found"

	# Define the image of home page carousel
	[[params.homeimg]]
	path = "img/loopbanner1.jpg"
	