baseURL = "http://example.org/"
languageCode = "en-us"
title = "Dream Possible"

theme = "hugo-steam"

[[menu.main]]
    name = "關於我們"
    pre = "<i class='fa fa-heart'></i>"
    weight = -110
    identifier = "aboutus"
    url = "/aboutus/"
[[menu.main]]
    name = "contactus"
    pre = "<i class='fa fa-road'></i>"
    weight = -1000
	identifier = "contactus"
    url = "/contactus/"
[[menu.main]]
    name = "course"
    pre = "<i class='fa fa-heart'></i>"
    weight = -110
    identifier = "course"
    url = "/course/"
[[menu.main]]
    name = "lifegrow"
    pre = "<i class='fa fa-road'></i>"
    weight = -100
	identifier = "lifegrow"
    url = "/lifegrow/"
[[menu.main]]
    name = "media"
    pre = "<i class='fa fa-heart'></i>"
    weight = -110
    identifier = "media"
    url = "/media/"
[[menu.main]]
    name = "payloveforward"
    pre = "<i class='fa fa-road'></i>"
    weight = -100
	identifier = "payloveforward"
    url = "/payloveforward/"

[params]
	title = "自在社"
	subtitle = "幸福/從感恩開始"
	copyright = "Released under the MIT license."

	# You can choose between green, orange, red and blue.
	themecolor = "green"

	# Link custom assets relative to /static
	favicon   = "favicon.ico"
	customCSS = []
	customJS  = []

	# To provide some metadata for search engines and the about section in the footer
	# feel free to add a few information about you and your website.
	name = "John Doe"
	bio = "programmer - blogger - coffee aficionado"
	description = "Your description of the blog"
	
	# Link your social networks (optional)
	location = ""
	#twitter = "spf13"
	linkedin = ""
	googleplus = ""
	facebook = ""
	instagram = ""
	#github = "spf13"
	gitlab = ""
	bitbucket = ""

	# Customize or translate the strings
	keepReadingStr = "Keep reading"
	backtotopStr = "Back to top"
	shareStr = "Share"
	pageNotFoundTitle = "404 - Page not found"

	# Define the image of home page carousel
	[[params.homeimg]]
	path = "http://cms.ipressroom.com.s3.amazonaws.com/173/files/20159/562fd133299b50089c0019a6_4932332761_9b2e62bfd4_b/4932332761_9b2e62bfd4_b_cef9a30b-856b-4b6a-9b97-0ea3bab71884-prv.jpg"
	[[params.homeimg]]
	path = "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Birnbaum_am_Lerchenberg_retouched.jpg/310px-Birnbaum_am_Lerchenberg_retouched.jpg"

	