---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
  media:
    default_front_matter_template: media
  course:
    default_front_matter_template: dp42
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: "/uploads"
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
version: 0.31.1
