---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/aboutus
  label: Aboutus
  create: all
  match: "**/*"
- type: directory
  path: content/contactus
  label: Contactus
  create: all
  match: "**/*"
- type: directory
  path: content/course
  label: Course
  create: all
  match: "**/*"
- type: directory
  path: content/lifegrow
  label: Lifegrow
  create: all
  match: "**/*"
- type: directory
  path: content/media
  label: Media
  create: all
  match: "**/*"
- type: directory
  path: content/payloveforward
  label: Payloveforward
  create: all
  match: "**/*"
- type: directory
  path: content/coachtoserve
  label: Coachtoserve
  create: all
  match: "**/*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: "/uploads"
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
build:
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
  publish_command: hugo -d public
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.31.1
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.31.1
  preview_output_directory: public
  output_directory: public
version: 0.31.1
