---
pages:
- coachtoserve/coachtoserve.md
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: menu
  label: Menu
  type: text
  hidden: true
  default: ''
- name: weight
  label: Weight
  type: text
  hidden: false
  default: 0
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
- type: datetime
- type: datetime
  name: date
  label: date
  hidden: true
  config:
    time_format: h:mm A
