---
pages:
- course/timetable/dp43-1.md
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: menu
  label: Menu
  type: text
  hidden: true
  default: ''
- name: weight
  label: Weight
  type: text
  hidden: false
  default: 0
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
- type: datetime
  name: date
  label: date
  hidden: true
  config:
    time_format: h:mm A
  default: 2017-12-31 16:00:00 +0000
